name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data preprocessing (smoke test)
        run: |
          python src/preprocessing.py

      - name: Run model training (smoke test)
        run: |
          python src/train.py

      - name: Build Docker image
        run: |
          docker build -t smart-energy-predictor . 